Vagrant.configure(2) do |config|
  config.vm.define "ansible-host" do |node|
        node.vm.box = "chef/centos-6.5-i386"
        node.vm.hostname = "ansible-host"
        node.vm.network :private_network, ip: "192.168.1.10"
  end
  if Vagrant.has_plugin?("vagrant-proxyconf")
    config.proxy.http = "http://tisproxy:8080/"
    config.proxy.https = "http://tisproxy:8080/"
    config.proxy.no_proxy = "localhost,127.0.0.1,192.168."
  end

end
